### ISSUE TITLE
Another FYI

### ISSUE THREAD

**Issue by svenanders** [sindresorhus/superb#24]
I have this repo called RantJS - https://github.com/svenanders/Rantjs that allows you to do all these things using grammar. 
Example: 
var rant = require("rantjs");
rant("<verb victory ed>"); // victorious verbs with an ed ending
// Succeeded

It would be easy to add all the superb words into the mix, and the upshot is that you'd get to use real grammar to create longer sentences. :)

Lots more examples, and a parser: http://rantjs.robbestad.com/

**Comment by sindresorhus** [comment]
That's pretty cool. Will keep it in mind :)

Might be a good fit for: https://github.com/sindresorhus/awesome-nodejs#natural-language-processing
